### ISSUE TITLE
登陆功能似乎失效了

### ISSUE THREAD

**Issue by spiedeman** [KivenCkl/LeetCode_Helper#2]
直接通过`requests`获取`cookies`的方法似乎失效了，登陆功能出了问题。

**Comment by KivenCkl** [comment]
> 直接通过`requests`获取`cookies`的方法似乎失效了，登陆功能出了问题。

抱歉，之前一直没看...现在已经修复了，leetcode有对接口进行修改，之后打算重新改写这个工具
