### ISSUE TITLE
限制爬虫 requests 请求频率，避免冻结账号

### ISSUE THREAD

**Issue by Singularity0909** [KivenCkl/LeetCode_Helper#6]
最近因为爬取提交记录过多被冻结账号

![image](https://user-images.githubusercontent.com/44798266/97841426-c23f0100-1d20-11eb-9bbe-61aabbb9979e.png)

**Comment by Singularity0909** [comment]
是否可以新增一个慢速请求的模式，设定在一定范围内随机的 sleep 时长

**Comment by KivenCkl** [comment]
> 是否可以新增一个慢速请求的模式，设定在一定范围内随机的 sleep 时长

这个有点危险，被封账号就有点划不来了。现在的速度已经挺慢的了。

**Comment by Singularity0909** [comment]
> > 是否可以新增一个慢速请求的模式，设定在一定范围内随机的 sleep 时长
> 
> 这个有点危险，被封账号就有点划不来了。现在的速度已经挺慢的了。

300+ 题几秒爬完，感觉还是不够慢 Orz 可以指明一下在哪里加上 sleep() 合适吗 我想让它延长到几分钟 这样肯定是安全的吧

**Comment by Singularity0909** [comment]
![1FD84B54-7BD4-4D72-8147-B2B28EB0E1DC](https://user-images.githubusercontent.com/44798266/98516247-3b050680-22a7-11eb-8283-d0098819b901.jpeg)
![6ED363D5-EC31-4E84-9447-5E40DFF44B51](https://user-images.githubusercontent.com/44798266/98516262-3f312400-22a7-11eb-8a2a-2d4ac8799449.jpeg)

🤣🤣
